version: "3.9"
services:
  tilkku_postgres:
    container_name: tilkku_postgres
    image: postgres
    env_file:
      - .env
    environment:
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data

  tilkku_redis:
    container_name: tilkku_redis
    image: redis
    restart: unless-stopped

  tilkku_web:
    container_name: tilkku_web
    build: .
    ports:
      - 8001:8000
    env_file:
      - .env
    environment:
      POSTGRES_HOST: tilkku_postgres
    restart: unless-stopped
    depends_on:
      - tilkku_postgres
      - tilkku_redis
    volumes:
      - ./app/tilkku:/code/tilkku:rw