version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_DB: ${DBNAME}
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data

  web:
    container_name: web
    build: .
    ports:
      - 8001:8000
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASS: ${DBPASS}
      POSTGRES_DBNAME: ${DBNAME}
      POSTGRES_HOST: postgres
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASS: ${ADMIN_PASS}
    restart: unless-stopped
    depends_on:
      - postgres